apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: electionwatch-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/description: "ElectionWatch Multi-Agent API Service"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - name: electionwatch-api
        image: gcr.io/PROJECT_ID/electionwatch-api:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        # Add your environment variables here:
        # - name: MONGODB_ATLAS_URI
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secret
        #       key: uri
        # - name: GOOGLE_CLOUD_PROJECT
        #   value: "your-project-id"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3 