version: '3.8'

services:
  # ElectionWatch API
  api:
    build:
      context: ..
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI:-}
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-}
    volumes:
      - ..:/app
    depends_on:
      - mongodb
      - neo4j
    restart: unless-stopped
    networks:
      - electionwatch-network

  # MongoDB for data storage
  mongodb:
    image: mongo:7
    container_name: electionwatch-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
      - ../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - electionwatch-network

  # Neo4j for graph data
  neo4j:
    image: neo4j:5
    container_name: electionwatch-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped
    networks:
      - electionwatch-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: electionwatch-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - electionwatch-network

  # Nginx reverse proxy (production-like setup)
  nginx:
    image: nginx:alpine
    container_name: electionwatch-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - electionwatch-network

volumes:
  mongodb_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  redis_data:
    driver: local

networks:
  electionwatch-network:
    driver: bridge 